#include <inc\sc_global.h>

#include <inc\sc_def.h>


void Equip_BANGS_Full(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_knife01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_knife01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_maceta01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_maceta01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\velka_polni\\EOP_e_pistolcase01.eqp";

	*count=8;
}

void Equip_BANGS_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_bangs\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=2;
}


void Equip_BRONSON_Full(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_e_canteen01_0.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_e_pistolcase01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\velka_polni\\EOP_hat1US_v01.eqp";

	*count=8;
}

void Equip_BRONSON_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\lehke_vybaveni\\EOP_e_canteen01_0.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_bronson\\lehke_vybaveni\\EOP_hat1US_v01.eqp";

	*count=3;
}


void Equip_CROCKER_Full(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat4US_v01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_hat4US_v01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigmedicbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_e_bigmedicbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_e_canteen01_0.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_glasses01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_e_glasses01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_medicbag01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_e_medicbag01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\velka_polni\\EOP_e_pistolcase01.eqp";

	*count=8;
}

void Equip_CROCKER_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_glasses01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\lehke_vybaveni\\EOP_e_glasses01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_medicbag01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\lehke_vybaveni\\EOP_e_medicbag01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_hat4US_v01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_crocker\\lehke_vybaveni\\EOP_hat4US_v01.eqp";

	*count=5;
}


void Equip_DEFORT_Full(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat2US_v01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\velka_polni\\EOP_hat2US_v01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_flashlight01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\velka_polni\\EOP_e_pistolcase01.eqp";

	*count=6;
}

void Equip_DEFORT_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_hat2US_v01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_defort\\lehke_vybaveni\\EOP_hat2US_v01.eqp";

	*count=3;
}


void Equip_HORNSTER_Full(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_pistolcase01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_canteen01_0.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_flashlight01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	*count=8;
}

void Equip_HORNSTER_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_hornster\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=2;
}


void Equip_NHUT_Full(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat3US_v02.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\velka_polni\\EOP_hat3US_v02.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_flashlight01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_maceta01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\velka_polni\\EOP_e_maceta01.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\velka_polni\\EOP_e_pistolcase01.eqp";

	*count=7;
}

void Equip_NHUT_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_hat3US_v02.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_nhut\\lehke_vybaveni\\EOP_hat3US_v02.eqp";

	*count=3;
}


void Equip_ROSENFIELD_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat4US_v02.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\EOP_UH14PH05_01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_rosenfield\\lehke_vybaveni\\EOP_e_ammoboxfp01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_rosenfield\\lehke_vybaveni\\EOP_e_ammoboxfp01_0.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_rosenfield\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_faidpouch01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_rosenfield\\lehke_vybaveni\\EOP_e_faidpouch01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_rosenfield\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=6;
}



void Equip_SF1_Full_Helmet(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_e_canteen01_0.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_e_m16ammobox01_1.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_hlmt1US_v03.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni\\EOP_hlmt1US_v03.eqp";

	*count=8;
}



void Equip_SF1_Full_Hat(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_hat1US_v01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_e_canteen01_0.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_faidpouch01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_e_faidpouch01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_e_littlebag01.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_e_m16ammobox01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\velka_polni2\\EOP_e_m16ammobox01_0.eqp";

	*count=8;
}

void Equip_SF1_Light_Hat(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\lehke_vybaveni\\EOP_e_canteen01_0.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_faidpouch01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\lehke_vybaveni\\EOP_e_faidpouch01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr01\\lehke_vybaveni\\EOP_hat1US_v01.eqp";

	*count=3;
}


void Equip_SF2_Full_Helmet(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_flashlight01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_e_m16ammobox01_1.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_e_m16ammobox01_2.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_hlmt1US_v01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni\\EOP_hlmt1US_v01.eqp";

	*count=8;
}



void Equip_SF2_Full_Hat(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_e_ammoboxfp01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_e_pistolcase01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_hat4US_v01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\velka_polni2\\EOP_hat4US_v01.eqp";

	*count=8;
}

void Equip_SF2_Light_Hat(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\lehke_vybaveni\\EOP_e_ammoboxfp01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_hat4US_v01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_SFgncsldr02\\lehke_vybaveni\\EOP_hat4US_v01.eqp";

	*count=4;
}


void Equip_LLDB1_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\lehke_vybaveni\\EOP_e_ammoboxfp01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v03.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\lehke_vybaveni\\EOP_hat1US_v03.eqp";

	*count=4;
}


void Equip_LLDB1_Full_ph08(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_maceta01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni\\EOP_e_maceta01.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_hlmt1US_v03.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni\\EOP_hlmt1US_v03.eqp";

	*count=7;
}


void Equip_LLDB1_Full_ph07(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_faidpouch01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_e_faidpouch01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_e_pistolcase01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_hat6US_v01.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr01\\velka_polni2\\EOP_hat6US_v01.eqp";

	*count=8;
}


void Equip_LLDB2_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat3US_v03.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\lehke_vybaveni\\EOP_hat3US_v03.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_faidpouch01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\lehke_vybaveni\\EOP_e_faidpouch01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\lehke_vybaveni\\EOP_e_littlebag01.eqp";

	*count=4;
}


void Equip_LLDB2_Full_ph01(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_flashlight01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_brt1US_v01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni\\EOP_brt1US_v01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni\\EOP_e_canteen01_0.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	*count=7;
}


void Equip_LLDB2_Full_ph03(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_e_m16ammobox01_0.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_faidpouch01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_e_faidpouch01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_knife01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_e_knife01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_e_littlebag01.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_e_m16ammobox01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_hat2US_v02.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_LLDBsldr02\\velka_polni2\\EOP_hat2US_v02.eqp";

	*count=8;
}


void Equip_CIDG1_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_flashlight01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\lehke_vybaveni\\EOP_e_flashlight01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_brt1US_v01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\lehke_vybaveni\\EOP_brt1US_v01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\lehke_vybaveni\\EOP_e_ammoboxfp01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=5;
}


void Equip_CIDG1_Full_ph03(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_faidpouch01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni\\EOP_e_faidpouch01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_hat2US_v02.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni\\EOP_hat2US_v02.eqp";

	*count=7;
}


void Equip_CIDG1_Full_ph04(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni2\\EOP_e_bigbag01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni2\\EOP_e_ammoboxfp01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni2\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni2\\EOP_e_canteen01_0.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni2\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni2\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_hat3US_v02.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr01\\velka_polni2\\EOP_hat3US_v02.eqp";

	*count=7;
}


void Equip_CIDG2_Light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat4US_v02.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\lehke_vybaveni\\EOP_hat4US_v02.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\lehke_vybaveni\\EOP_e_littlebag01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=4;
}


void Equip_CIDG2_Full_ph08(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_knife01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni\\EOP_e_knife01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_bigbag01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_hlmt1US_v02.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni\\EOP_hlmt1US_v02.eqp";

	*count=7;
}


void Equip_CIDG2_Full_ph02(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_e_ammoboxfp01.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_e_ammoboxfp01.eqp";

	eqp[1].bes = "G\\Equipment\\US\\bes\\EOP_e_canteen01.BES";
	eqp[1].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\Equipment\\US\\bes\\EOP_e_littlebag01.BES";
	eqp[2].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_e_littlebag01.eqp";

	eqp[3].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[3].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\Equipment\\US\\bes\\EOP_e_m16ammobox01.BES";
	eqp[4].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_e_m16ammobox01_0.eqp";

	eqp[5].bes = "G\\Equipment\\US\\bes\\EOP_e_pistolcase01.BES";
	eqp[5].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_e_pistolcase01.eqp";

	eqp[6].bes = "G\\Equipment\\US\\bes\\EOP_e_shovel01.BES";
	eqp[6].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_e_shovel01.eqp";

	eqp[7].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v02.BES";
	eqp[7].eqp = "G\\Equipment\\US\\eqp\\CUP_CIDGsldr02\\velka_polni2\\EOP_hat1US_v02.eqp";

	*count=8;
}


void Equip_dinstructor_Engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_sunglasses02.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_sunglasses02.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_m16ammobox01_0.eqp";

	*count=6;
}

void Equip_dinstructor_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_knife01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\machinegunner\\EOP_e_knife01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\machinegunner\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\machinegunner\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\machinegunner\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\machinegunner\\EOP_e_m16ammobox01_0.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_2.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\machinegunner\\EOP_e_m16ammobox01_2.eqp";

	*count=6;
}


void Equip_dinstructor_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigmedicbag01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\medic\\EOP_e_bigmedicbag01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\medic\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\medic\\EOP_e_canteen01_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_glasses01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\medic\\EOP_e_glasses01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\medic\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_medicbag01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\medic\\EOP_e_medicbag01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\medic\\EOP_e_pistolcase01.eqp";

	*count=7;
}


void Equip_dinstructor_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_radio01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\radioman\\EOP_radio01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_radioear01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\radioman\\EOP_e_radioear01_x.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\radioman\\EOP_e_pistolcase01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_2.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\radioman\\EOP_e_m16ammobox01_2.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\radioman\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\radioman\\EOP_e_canteen01.eqp";

	*count=6;
}

void Equip_dinstructor_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_maceta01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\sniper\\EOP_e_maceta01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\sniper\\EOP_e_pistolcase01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\sniper\\EOP_e_m16ammobox01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\sniper\\EOP_e_m16ammobox01_0.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\sniper\\EOP_e_canteen01_0.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\sniper\\EOP_e_littlebag01.eqp";

	*count=6;
}

void Equip_dinstructor_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\soldier\\EOP_e_littlebag01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\soldier\\EOP_e_canteen01_0.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\soldier\\EOP_e_flashlight01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\soldier\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\soldier\\EOP_e_m16ammobox01_0.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\soldier\\EOP_e_pistolcase01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_shovel01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\soldier\\EOP_e_shovel01.eqp";

	*count=7;
}


void Equip_douglas_engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_sunglasses01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\engineer\\EOP_e_sunglasses01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\engineer\\EOP_e_m16ammobox01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\engineer\\EOP_e_m16ammobox01_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\engineer\\EOP_e_bigbag01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\engineer\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\engineer\\EOP_e_canteen01.eqp";

	*count=6;
}


void Equip_douglas_light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat3US_v03.bes";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\EOP_UH15PH04_01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_faidpouch01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\Lehke_vybaveni\\EOP_e_faidpouch01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\Lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\Lehke_vybaveni\\EOP_e_flashlight01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\Lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=5;
}


void Equip_douglas_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_knife01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\machineguner\\EOP_e_knife01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\machineguner\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\machineguner\\EOP_e_m16ammobox01_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\machineguner\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_1.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\machineguner\\EOP_e_m16ammobox01_1.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\machineguner\\EOP_e_canteen01.eqp";

	*count=6;
}


void Equip_douglas_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_glasses01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\medic\\EOP_e_glasses01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_medicbag01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\medic\\EOP_e_medicbag01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigmedicbag01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\medic\\EOP_e_bigmedicbag01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\medic\\EOP_e_canteen01_0.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\medic\\EOP_e_canteen01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\medic\\EOP_e_m16ammobox01_0.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\medic\\EOP_e_pistolcase01.eqp";

	*count=7;
}


void Equip_douglas_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_radioear01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\radioman\\EOP_e_radioear01_x.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\radioman\\EOP_e_pistolcase01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\radioman\\EOP_e_m16ammobox01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\radioman\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_radio01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\radioman\\EOP_radio01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\radioman\\EOP_e_canteen01.eqp";

	*count=6;
}


void Equip_douglas_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_maceta01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\sniper\\EOP_e_maceta01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\sniper\\EOP_e_pistolcase01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\sniper\\EOP_e_m16ammobox01_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_1.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\sniper\\EOP_e_m16ammobox01_1.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\sniper\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\sniper\\EOP_e_canteen01_0.eqp";

	*count=6;
}


void Equip_douglas_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\soldier\\EOP_e_flashlight01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\soldier\\EOP_e_pistolcase01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\soldier\\EOP_e_m16ammobox01_1.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\soldier\\EOP_e_m16ammobox01_0.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\soldier\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\soldier\\EOP_e_canteen01_0.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_shovel01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\soldier\\EOP_e_shovel01.eqp";

	*count=7;
}


void Equip_douglas_big(s_SC_P_CreateEqp *eqp, int *count){
    eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat3US_v03.bes";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\EOP_UH15PH04_01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_faidpouch01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\velka_polni\\EOP_e_faidpouch01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[7].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[7].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Douglas\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	*count=8;
}


void Equip_huntV2_light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\Lehke_vybaveni\\EOP_e_canteen01_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_ammoboxfp01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\Lehke_vybaveni\\EOP_e_ammoboxfp01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\Lehke_vybaveni\\EOP_e_flashlight01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\Lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=4;
}


void Equip_huntV2_big(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\bes\\EOP_e_faidpouch01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\velka_polni\\EOP_e_faidpouch01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\velka_polni\\EOP_e_canteen01_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_hunter_v2\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	*count=7;
}


void Equip_Nham_light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v02.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\EOP_UH18PH02_01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_ammoboxfp01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_ammoboxfp01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_flashlight01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	*count=5;
}


void Equip_Nham_big(s_SC_P_CreateEqp *eqp, int *count){
    eqp[0].bes = "G\\Equipment\\US\\bes\\EOP_hat1US_v02.BES";
	eqp[0].eqp = "G\\Equipment\\US\\eqp\\EOP_UH18PH02_01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_ammoboxfp01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_ammoboxfp01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_faidpouch01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_faidpouch01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[7].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[7].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[8].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[8].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	*count=9;
}


void Equip_SFgncsldr03_engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_sunglasses02.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_sunglasses02.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_m16ammobox01_0.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_m16ammobox01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_littlebag01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_canteen01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\engineer\\EOP_e_bigbag01.eqp";

	*count=6;
}


void Equip_SFgncsldr03_light(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_ammoboxfp01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_ammoboxfp01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_flashlight01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_pistolcase01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_Nham\\Lehke_vybaveni\\EOP_e_canteen01.eqp";

	*count=4;
}


void Equip_SFgncsldr03_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_knife01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\machineguner\\EOP_e_knife01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\machineguner\\EOP_e_m16ammobox01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\machineguner\\EOP_e_m16ammobox01_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_1.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\machineguner\\EOP_e_m16ammobox01_1.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\machineguner\\EOP_e_bigbag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\machineguner\\EOP_e_canteen01.eqp";

	*count=6;
}


void Equip_SFgncsldr03_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigmedicbag01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\medic\\EOP_e_bigmedicbag01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\medic\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\medic\\EOP_e_canteen01_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_glasses01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\medic\\EOP_e_glasses01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\medic\\EOP_e_m16ammobox01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_medicbag01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\medic\\EOP_e_medicbag01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\medic\\EOP_e_pistolcase01.eqp";

	*count=7;
}


void Equip_SFgncsldr03_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_radioear01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\radioman\\EOP_e_radioear01_x.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_radio01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\radioman\\EOP_radio01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\radioman\\EOP_e_pistolcase01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\radioman\\EOP_e_m16ammobox01_0.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\radioman\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\radioman\\EOP_e_canteen01.eqp";

	*count=6;
}


void Equip_SFgncsldr03_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\sniper\\EOP_e_pistolcase01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_maceta01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\sniper\\EOP_e_maceta01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\sniper\\EOP_e_m16ammobox01_1.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\sniper\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\sniper\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\sniper\\EOP_e_canteen01_0.eqp";

	*count=6;
}


void Equip_SFgncsldr03_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\soldier\\EOP_e_littlebag01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_1.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\soldier\\EOP_e_m16ammobox01_1.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\soldier\\EOP_e_m16ammobox01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_shovel01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\soldier\\EOP_e_shovel01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\soldier\\EOP_e_flashlight01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01_0.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\soldier\\EOP_e_canteen01_0.eqp";

	*count=6;
}


void  Equip_SFgncsldr03_full(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_faidpouch01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni\\EOP_e_faidpouch01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni\\EOP_e_bigbag01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni\\EOP_e_canteen01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_flashlight01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni\\EOP_e_flashlight01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni\\EOP_e_littlebag01.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni\\EOP_e_m16ammobox01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni\\EOP_e_m16ammobox01_0.eqp";

	*count=7;
}


void Equip_SFgncsldr03_full2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_ammoboxfp01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni2\\EOP_e_ammoboxfp01.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_canteen01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni2\\EOP_e_canteen01.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_littlebag01.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni2\\EOP_e_littlebag01.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni2\\EOP_e_m16ammobox01.eqp";

	eqp[4].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_m16ammobox01_0.bes";
	eqp[4].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni2\\EOP_e_m16ammobox01_0.eqp";

	eqp[5].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_pistolcase01.bes";
	eqp[5].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni2\\EOP_e_pistolcase01.eqp";

	eqp[6].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_shovel01.bes";
	eqp[6].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_SFgncsldr03\\velka_polni2\\EOP_e_shovel01.eqp";

	*count=7;
}