#include <inc\sc_global.h>

#include <inc\sc_def.h>


void Equip_blckpjmsVC01_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC01\\vybaveni1\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC01\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC01_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mdclbag01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC01\\vybaveni2\\EOP_e_mdclbag01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC01\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC02_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_bigbag01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC02\\vybaveni1\\EOP_e_bigbag01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC02\\vybaveni1\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC02_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC02\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC02\\vybaveni2\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC03_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mdclbag01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC03\\vybaveni1\\EOP_e_mdclbag01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC03\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC03_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC03\\vybaveni2\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC03\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC04_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC04\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC04\\vybaveni1\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC04_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC04\\vybaveni2\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_blckpjmsVC04\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	*count=2;
}


void Equip_NVAsoldier02_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier02\\vybaveni1\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_bigbag01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier02\\vybaveni1\\EOP_e_bigbag01VC.eqp";

	*count=2;
}


void Equip_NVAsoldier02_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier02\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mdclbag01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier02\\vybaveni2\\EOP_e_mdclbag01VC.eqp";

	*count=2;
}


void Equip_NVAsoldier03_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier03\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier03\\vybaveni1\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_NVAsoldier03_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier03\\vybaveni2\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_NVAsoldier03\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	*count=2;
}


void Equip_uniformVC01_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC01\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC01\\vybaveni1\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_uniformVC01_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC01\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mdclbag01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC01\\vybaveni2\\EOP_e_mdclbag01VC.eqp";

	*count=2;
}


void Equip_uniformVC02_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC02\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC02\\vybaveni1\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_uniformVC02_Vyb2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC02\\vybaveni2\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC02\\vybaveni2\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_uniformVC03_Vyb1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_mgznpouch01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC03\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_bigbag01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC03\\vybaveni1\\EOP_e_bigbag01VC.eqp";

	*count=2;
}


void Equip_uniformVC03_Vyb2(s_SC_P_CreateEqp *eqp, int *count){

	eqp[0].bes = "G\\Equipment\\VC\\bes\\EOP_e_canteen01VC.BES";
	eqp[0].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC03\\vybaveni2\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\Equipment\\VC\\bes\\EOP_e_mdclbag01VC.BES";
	eqp[1].eqp = "G\\Equipment\\VC\\eqp\\CVP_uniformVC03\\vybaveni2\\EOP_e_mdclbag01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC05_engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\engineer\\EOP_e_bigbag01VC.eqp";

	*count=1;
}


void Equip_blckpjmsVC05_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\machineguner\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\machineguner\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\machineguner\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\machineguner\\EOP_e_mgznpouch01VC_2.eqp";

	*count=4;
}


void Equip_blckpjmsVC05_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_1.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\medic\\EOP_e_canteen01VC_1.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\medic\\EOP_e_mdclbag01VC.eqp";

	*count=2;
}


void Equip_blckpjmsVC05_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_vc_radioear01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\radioman\\EOP_vc_radioear01_x.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOJ_vc_radio_3pv.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\radioman\\EOJ_vc_radio_3pv.eqp";

	*count=2;
}


void Equip_blckpjmsVC05_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\sniper\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\sniper\\EOP_e_canteen01VC_0.eqp";

	*count=2;
}


void Equip_blckpjmsVC05_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\soldier\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\soldier\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\soldier\\EOP_e_canteen01VC_1.eqp";

	*count=3;
}


void Equip_blckpjmsVC05_vybaveni1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\vybaveni1\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\vybaveni1\\EOP_e_mgznpouch01VC_0.eqp";

	*count=3;
}


void Equip_blckpjmsVC05_vybaveni2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\vybaveni2\\EOP_e_canteen01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\vybaveni2\\EOP_e_mdclbag01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_blckpjmsVC05\\vybaveni2\\EOP_e_bigbag01VC.eqp";

	*count=3;
}


void Equip_NVAcolonel_engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\engineer\\EOP_e_bigbag01VC.eqp";

	*count=1;
}


void Equip_NVAcolonel_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\machineguner\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\machineguner\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\machineguner\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\machineguner\\EOP_e_mgznpouch01VC_2.eqp";

	*count=4;
}


void Equip_NVAcolonel_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\medic\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\medic\\EOP_e_mdclbag01VC.eqp";

	*count=2;
}


void Equip_NVAcolonel_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOJ_vc_radio_3pv.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\medic\\EOJ_vc_radio_3pv.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_vc_radioear01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\medic\\EOP_vc_radioear01_x.eqp";

	*count=2;
}


void Equip_NVAcolonel_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\sniper\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\sniper\\EOP_e_canteen01VC_0.eqp";

	*count=2;
}


void Equip_NVAcolonel_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\soldier\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\soldier\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAcolonel\\soldier\\EOP_e_canteen01VC.eqp";

	*count=3;
}


void Equip_NVAsoldier02_engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Us\\bes\\EOP_e_bigbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Us\\eqp\\CUP_dinstructor\\engineer\\EOP_e_bigbag01VC.eqp";

	*count=1;
}


void Equip_NVAsoldier02_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\machineguner\\EOP_e_mgznpouch01VC_2.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\machineguner\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\machineguner\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\machineguner\\EOP_e_mgznpouch01VC_1.eqp";

	*count=4;
}


void Equip_NVAsoldier02_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\medic\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\medic\\EOP_e_mdclbag01VC.eqp";

	*count=2;
}


void Equip_NVAsoldier02_radioman(s_SC_P_CreateEqp *eqp, int *count){
    eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_vc_radioear01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\radioman\\EOP_vc_radioear01_x.eqp";	

    eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOJ_vc_radio_3pv.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\radioman\\EOJ_vc_radio_3pv.eqp";

	*count=2;
}


void Equip_NVAsoldier02_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\sniper\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\sniper\\EOP_e_mgznpouch01VC_0.eqp";

	*count=2;
}


void Equip_NVAsoldier02_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\soldier\\EOP_e_mgznpouch01VC_2.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\soldier\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\soldier\\EOP_e_canteen01VC.eqp";

	*count=3;
}


void Equip_NVAsoldier03_engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier02\\engineer\\EOP_e_bigbag01VC.eqp";

	*count=1;
}


void Equip_NVAsoldier03_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\machineguner\\EOP_e_mgznpouch01VC_2.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\machineguner\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\machineguner\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\machineguner\\EOP_e_mgznpouch01VC_1.eqp";

	*count=4;
}


void Equip_NVAsoldier03_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\medic\\EOP_e_mdclbag01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\medic\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_NVAsoldier03_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_vc_radioear01.bes"
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\radioman\\EOP_vc_radioear01_x.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOJ_vc_radio_3pv.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\radioman\\EOJ_vc_radio_3pv.eqp";

	*count=2;
}


void Equip_NVAsoldier03_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\sniper\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\sniper\\EOP_e_canteen01VC_0.eqp";

	*count=2;
}


void Equip_NVAsoldier03_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\soldier\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\soldier\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier03\\soldier\\EOP_e_canteen01VC.eqp";

	*count=3;
}


void Equip_NVAsoldier04_engineer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\engineer\\EOP_e_bigbag01VC.eqp";

	*count=1;
}


void Equip_NVAsoldier04_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\machineguner\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\machineguner\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\machineguner\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\machineguner\\EOP_e_mgznpouch01VC_2.eqp";

	*count=4;
}


void Equip_NVAsoldier04_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_1.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\medic\\EOP_e_canteen01VC_1.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\medic\\EOP_e_mdclbag01VC.eqp";

	*count=2;
}


void Equip_NVAsoldier04_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOJ_vc_radio_3pv.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\radioman\\EOJ_vc_radio_3pv.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_vc_radioear01.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\radioman\\EOP_vc_radioear01_x.eqp";

	*count=2;
}


void Equip_NVAsoldier04_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\sniper\\EOP_e_canteen01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\sniper\\EOP_e_mgznpouch01VC_0.eqp";

	*count=2;
}


void Equip_NVAsoldier04_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_1.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\soldier\\EOP_e_canteen01VC_1.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\soldier\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\soldier\\EOP_e_mgznpouch01VC_1.eqp";

	*count=3;
}


void Equip_NVAsoldier04_vybaveni1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
    eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni1\\EOP_e_canteen01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni1\\EOP_e_mgznpouch01VC_0.eqp";

	*count=3;
}


void Equip_NVAsoldier04_vybaveni2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\vybaveni2\\EOP_e_canteen01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\vybaveni2\\EOP_e_mdclbag01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_NVAsoldier04\\vybaveni2\\EOP_e_bigbag01VC.eqp";

	*count=3;
}


void Equip_poorVC04_engineeer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\engineer\\EOP_e_bigbag01VC.eqp";

	*count=1;
}


void Equip_poorVC04_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\machinegunner\\EOP_e_mgznpouch01VC_2.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\machinegunner\\EOP_e_mgznpouch01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\machinegunner\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\machinegunner\\EOP_e_mgznpouch01VC_1.eqp";

	*count=4;
}


void Equip_poorVC04_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\medic\\EOP_e_mdclbag01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.eqp";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\medic\\EOP_e_canteen01VC.eqp";

	*count=2;
}


void Equip_poorVC04_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_vc_radioear01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\radioman\\EOP_vc_radioear01_x.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOJ_vc_radio_3pv.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\radioman\\EOJ_vc_radio_3pv.eqp";

	*count=2;
}


void Equip_poorVC04_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\sniper\\EOP_e_canteen01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\sniper\\EOP_e_mgznpouch01VC_0.eqp";

	*count=2;
}


void Equip_poorVC04_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\soldier\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\soldier\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_poorVC04\\soldier\\EOP_e_canteen01VC.eqp";

	*count=3;
}


void Equip_uniformVC04_engineeer(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\engineeer\\EOP_e_bigbag01VC.eqp";

	*count=1;
}


oid Equip_uniformVC04_machinegun(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\machineguner\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\machineguner\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\machineguner\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[3].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_2.bes";
	eqp[3].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\machineguner\\EOP_e_mgznpouch01VC_2.eqp";

	*count=4;
}


void Equip_uniformVC04_medic(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\medic\\EOP_e_mdclbag01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_1.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\medic\\EOP_e_canteen01VC_1.eqp";

	*count=2;
}


void Equip_uniformVC04_radioman(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_vc_radioear01.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\radioman\\EOP_vc_radioear01_x.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOJ_vc_radio_3pv.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\radioman\\EOJ_vc_radio_3pv.eqp";

	*count=2;
}


void Equip_uniformVC04_sniper(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\sniper\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\sniper\\EOP_e_canteen01VC_0.eqp";

	*count=2;
}


void Equip_uniformVC04_soldier(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\soldier\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_1.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\soldier\\EOP_e_mgznpouch01VC_1.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_1.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\soldier\\EOP_e_canteen01VC_1.eqp";

	*count=3;
}


void Equip_uniformVC04_vybaveni1(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni1\\EOP_e_mgznpouch01VC.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mgznpouch01VC_0.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni1\\EOP_e_mgznpouch01VC_0.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni1\\EOP_e_canteen01VC.eqp";

	*count=3;
}


void Equip_uniformVC04_vybaveni2(s_SC_P_CreateEqp *eqp, int *count){
	eqp[0].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_canteen01VC_0.bes";
	eqp[0].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni2\\EOP_e_canteen01VC_0.eqp";

	eqp[1].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_mdclbag01VC.bes";
	eqp[1].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni2\\EOP_e_mdclbag01VC.eqp";

	eqp[2].bes = "G\\EQUIPMENT\\Vc\\bes\\EOP_e_bigbag01VC.bes";
	eqp[2].eqp = "G\\EQUIPMENT\\Vc\\eqp\\CVP_uniformVC04\\vybaveni2\\EOP_e_bigbag01VC.eqp";

	*count=3;
}